import os

DEBUG = False
TESTING = False
SQLALCHEMY_DATABASE_URI = os.environ.get('SQLALCHEMY_DATABASE_URI')
SQLALCHEMY_ECHO = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = os.environ.get('SECRET_KEY')
CSRF_ENABLED = True
WTF_CSRF_ENABLED = CSRF_ENABLED
MAX_CONTENT_LENGTH = 1024 * 1024  # 1 MB max upload size
REDIS_URL = os.environ.get('REDIS_URL')

# flatpages
FLATPAGES_EXTENSION = '.html.md'
FLATPAGES_MARKDOWN_EXTENSIONS = []

# babel
BABEL_DEFAULT_LOCALE = 'pl'
BABEL_DEFAULT_TIMEZONE = 'Europe/Warsaw'

# file uploads
ALLOWED_UPLOAD_EXTENSIONS = ('.md', '.gfm', '.markdown')
UPLOAD_DIR_NAME = 'uploads'

# sentry
SENTRY_PUBKEY = os.environ.get('SENTRY_PUBKEY')
SENTRY_PROJECT = os.environ.get('SENTRY_PROJECT')

# emails
EMAIL_CONFIRMATION_SALT = os.environ.get('EMAIL_CONFIRMATION_SALT')
CONFIRMATION_TOKEN_MAX_AGE = 86400  # 24 hours
MAILGUN_DOMAIN = os.environ.get('MAILGUN_DOMAIN')
MAILGUN_API_KEY = os.environ.get('MAILGUN_API_KEY')
MAILGUN_API_BASE_URL = f'https://api.eu.mailgun.net/v3/{MAILGUN_DOMAIN}'
MAILGUN_MESSAGES_URL = f'{MAILGUN_API_BASE_URL}/messages'
MAILGUN_AUTH = ('api', MAILGUN_API_KEY)
MAIL_FROM = f'Devlog <devlog@{MAILGUN_DOMAIN}>'
