version: 2

updates:

  # Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily

  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: daily
