exclude_paths:
  - '*'
  - 'docs/**'
  - 'tests/**'
  - 'src/devlog/_version.py'
  - 'src/devlog/config.py'
  - 'src/devlog/wsgi.py'
  - 'src/devlog/secrets/**'
  - 'src/devlog/static/**'
  - 'src/devlog/templates/**'
