version: "2"
plugins:
  git-legal:
    enabled: true
exclude_patterns:
  - "docs/"
  - "tests/"
  - "secrets/"
  - "**/_version.py"
  - "**/wsgi.py"
  - "**/config*.py"
  - "**/app.py"
  - "**/cli.py"
  - "**/ext.py"
  - "**/__init__.py"
  - "versioneer.py"
  - "setup.py"
  - "**/static/"
  - "**/translations/"
  - "**/templates/"
checks:
  argument-count:
    config:
      threshold: 8
  method-complexity:
    config:
      threshold: 10
