version: "2"
exclude_patterns:
  - "docs/"
  - "tests/"
  - "conf/"
  - "src/devlog/static/vendor/"
  - 'src/devlog/wsgi.py'
  - 'src/devlog/app.py'
  - 'src/devlog/rqsettings.py'
plugins:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
          mass_threshold: 45
checks:
  argument-count:
    config:
      threshold: 8
  method-complexity:
    config:
      threshold: 10
