language: python
cache: pip
python:
  - "3.7"
  - "3.8"
install:
  - pip install -U -r requirements/test.txt
  - pip install -U Sphinx wheel
  - pip install -e .
  - pip install -U codacy-coverage
script:
  - pytest --cov-branch --cov-report xml --cov=devlog tests
  - python setup.py build_sphinx
  - python setup.py sdist bdist_wheel
after_success:
  - python-codacy-coverage -r coverage.xml
deploy:
  - provider: pages
    local-dir: build/sphinx/html
    committer-from-gh: true
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    on:
      branch: master
  - provider: releases
    api_key: $GH_TOKEN
    skip_cleanup: true
    file_glob: true
    file: dist/*
    on:
      tags: true
