os: linux
language: python
cache: pip
git:
  quiet: true
python:
  - "3.7"
  - "3.8"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - pip install -q -U -e .[test]
  - pip install -q -U Sphinx wheel
script:
  - pytest --cov-branch --cov-report xml --cov=devlog tests
  - python setup.py -q build_sphinx
  - python setup.py -q sdist bdist_wheel
after_script:
  - test $TRAVIS_PYTHON_VERSION = "3.8" && ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
deploy:
  - provider: pages
    local_dir: build/sphinx/html
    committer_from_gh: true
    cleanup: false
    token: $GH_TOKEN
    keep_history: true
    on:
      branch: master
      python: "3.8"
  - provider: releases
    token: $GH_TOKEN
    cleanup: false
    file_glob: true
    file: dist/*
    on:
      tags: true
      python: "3.7"
