dist: xenial
language: python
cache: pip
python:
  - "3.7"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - pip install -U -r requirements-test.txt
  - pip install -U Sphinx wheel
  - pip install -e .
  - pip install -U codacy-coverage
script:
  - pytest --cov-branch --cov-report xml --cov=devlog tests
  - make -C docs -f Makefile html
  - python setup.py sdist bdist_wheel
after_script:
  - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
after_success:
  - python-codacy-coverage -r coverage.xml
deploy:
  - provider: pages
    local-dir: docs/_build/html
    committer-from-gh: true
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    on:
      branch: master
  - provider: releases
    api_key: $GH_TOKEN
    skip_cleanup: true
    file_glob: true
    file: dist/*
    on:
      tags: true
